In [ ]:
pip install faiss-cpu

In [ ]:
import numpy as np
import faiss
import time
import gc

In [ ]:
dimension = 1000
n_vectors = 1000000
xb = np.random.random((n_vectors, dimension)).astype('float32')
xq = np.random.random((10, dimension)).astype('float32')

Flat array search

In [ ]:
start = time.time()
flat_index = faiss.IndexFlatL2(dimension)
flat_index.add(xb)
print("time is ",time.time()-start,"seconds")

time is  3.8793187141418457 seconds


In [ ]:
start = time.time()
distances, indices = flat_index.search(xq, 5)
print("time is ",time.time()-start,"seconds")
print("distances ",distances)
print("indices ",indices)

time is  3.828599691390991 seconds
distances  [[140.45319 140.88046 140.99254 141.2656  141.84497]
 [138.96826 139.5283  140.12866 140.74976 141.58244]
 [139.9488  139.9679  140.41019 140.86226 141.12714]
 [141.74536 141.9487  142.21146 142.95471 143.02533]
 [139.4109  140.64973 141.67291 141.78806 141.99573]
 [140.49    141.66821 141.92914 142.1541  142.26938]
 [137.61118 138.09189 139.11163 139.11267 139.32349]
 [137.46533 137.51218 138.68909 140.07156 140.672  ]
 [138.54924 140.87851 141.37926 141.65752 142.4866 ]
 [139.19962 139.29083 139.29547 139.40839 139.50372]]
indices  [[514292 207285  29494 969708 693720]
 [931011 233343 572082 523288 892400]
 [647430 805912 116585 954401 508980]
 [867616 645006 170386 250089 369179]
 [996223 524708 709859 204664 695563]
 [680728 450741 842199 167990 151768]
 [267993 765016 488349 131836 378367]
 [318995 358876 799134 979827 273196]
 [490156 717047  49102 361679 441425]
 [782071 132964 921189 884662 950344]]


In [ ]:
del flat_index
gc.collect()

0

Clustering

In [ ]:
start = time.time()
quantizer = faiss.IndexFlatL2(dimension)
clus_index = faiss.IndexIVFFlat(quantizer, dimension, 100)
clus_index.train(xb)
clus_index.add(xb)
print("time is ",time.time()-start,"seconds")

time is  13.879900693893433 seconds


In [ ]:
start = time.time()
distances,indices = clus_index.search(xq,5)
print("time is ",time.time()-start,"seconds")
print("distances ",distances)
print("indices ",indices)

time is  0.055008888244628906 seconds
distances  [[140.45319 141.84497 143.06863 143.54189 143.86989]
 [140.74976 144.72743 145.04489 145.63687 146.23341]
 [142.69383 143.73917 144.06125 144.2284  145.1484 ]
 [143.22475 146.81027 147.07648 147.67958 147.91669]
 [145.1141  145.16516 145.59131 146.50858 146.69907]
 [142.98587 145.36359 145.49944 145.93494 146.42584]
 [140.14462 143.11426 143.61479 143.71814 144.43239]
 [141.45657 143.40704 143.44589 144.15422 144.85278]
 [138.54924 144.8486  145.66728 146.20683 146.63391]
 [140.74097 143.8489  144.51971 144.55945 145.18253]]
indices  [[514292 693720 838447 959394 665093]
 [523288 674487  60571 708250 774946]
 [421876 673878  79628 910012 714804]
 [206824 595357 388238 734191 604226]
 [807293 953341   2306 836799 620001]
 [171951 316214 444496 685846 478084]
 [253579 226280 590968   9580  20988]
 [192680  44973 518234 858235 394240]
 [490156 554910  80939 411895 384455]
 [885010 908080 451946 314343 982594]]
